language: cpp
compiler: g++
sudo: require

dist: xenial

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - sudo apt update
  - sudo apt install g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 40

script:
  - make && make test_run
  - git ls-files src/ | xargs clang-format -i && git diff --exit-code
  - git ls-files test/ | xargs clang-format -i && git diff --exit-code





#language: cpp
#script:
#  - make
#  - git ls-files src/ | xargs clang-format -i && git diff --exit-code
#  - git ls-files test/ | xargs clang-format -i && git diff --exit-code
#compiler: g++
#dist: xenial
